package CS4262;

import CS4262.Core.SearchInitializer;
import CS4262.Models.Node;
import CS4262.Network.BSConnector;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Lahiru Kaushalya
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static MainFrame instance;
    private BSConnector bsConnector;

    public static MainFrame getInstance() {
        if(instance == null){
            MainFrame.instance = new MainFrame();
        }
        return instance;
    }
    
    private MainFrame() {
        initComponents();
        this.setResizable(false);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize(); //Set frame position
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        unregBtn.setEnabled(false);
        setDefaultText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainTab = new javax.swing.JTabbedPane();
        homeTab = new javax.swing.JTabbedPane();
        connectionPanel = new javax.swing.JPanel();
        ipLbl = new javax.swing.JLabel();
        portLabel = new javax.swing.JLabel();
        ipTextField = new javax.swing.JTextField();
        portTextField = new javax.swing.JTextField();
        regtBtn = new javax.swing.JButton();
        connectScrollPane = new javax.swing.JScrollPane();
        connectTextPane = new javax.swing.JTextPane();
        bsServerIPLbl = new javax.swing.JLabel();
        bsServerIPTextField = new javax.swing.JTextField();
        unregBtn = new javax.swing.JButton();
        detailsPanel = new javax.swing.JPanel();
        detailsScrollPane = new javax.swing.JScrollPane();
        details_contentTextPane = new javax.swing.JTextPane();
        details_nodeDetailsLbl = new javax.swing.JLabel();
        details_nodeConentLbl = new javax.swing.JLabel();
        details_idLbl = new javax.swing.JLabel();
        details_idDisplayLbl = new javax.swing.JLabel();
        details_ipDisplayLbl = new javax.swing.JLabel();
        details_ipLbl = new javax.swing.JLabel();
        details_portLbl = new javax.swing.JLabel();
        details_portDisplayLbl = new javax.swing.JLabel();
        details_successorLbl = new javax.swing.JLabel();
        details_succidDisplayLbl = new javax.swing.JLabel();
        details_succidLbl = new javax.swing.JLabel();
        details_succipLbl = new javax.swing.JLabel();
        details_succipDisplayLbl = new javax.swing.JLabel();
        details_succportDisplayLbl = new javax.swing.JLabel();
        details_succportLbl = new javax.swing.JLabel();
        details_successorLbl1 = new javax.swing.JLabel();
        details_succidLbl1 = new javax.swing.JLabel();
        details_preidDisplayLbl = new javax.swing.JLabel();
        details_preipLbl = new javax.swing.JLabel();
        details_preipDisplayLbl = new javax.swing.JLabel();
        details_preportLbl = new javax.swing.JLabel();
        details_preportDisplayLbl = new javax.swing.JLabel();
        routingTablePanel = new javax.swing.JPanel();
        routingScrollPane = new javax.swing.JScrollPane();
        routingTextPane = new javax.swing.JTextPane();
        indexTab = new javax.swing.JTabbedPane();
        fileIndexScrollPane = new javax.swing.JScrollPane();
        fileIndexTextPane = new javax.swing.JTextPane();
        wordIndexScrollPane = new javax.swing.JScrollPane();
        wordIndexTextPane = new javax.swing.JTextPane();
        searchPanel = new javax.swing.JPanel();
        downloadBtn = new javax.swing.JButton();
        fileNameTextField = new javax.swing.JTextField();
        searchScrollPane = new javax.swing.JScrollPane();
        searchTextPane = new javax.swing.JTextPane();
        searchBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);

        MainTab.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        MainTab.setAutoscrolls(true);
        MainTab.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        MainTab.setOpaque(true);

        ipLbl.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        ipLbl.setText("IP Address");

        portLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        portLabel.setText("Port");

        regtBtn.setText("REGISTER");
        regtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regtBtnActionPerformed(evt);
            }
        });

        connectTextPane.setEditable(false);
        connectScrollPane.setViewportView(connectTextPane);

        bsServerIPLbl.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bsServerIPLbl.setText("BS Server IP");

        unregBtn.setText("UNREGISTER");
        unregBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unregBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout connectionPanelLayout = new javax.swing.GroupLayout(connectionPanel);
        connectionPanel.setLayout(connectionPanelLayout);
        connectionPanelLayout.setHorizontalGroup(
            connectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, connectionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(connectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(connectScrollPane)
                    .addGroup(connectionPanelLayout.createSequentialGroup()
                        .addGroup(connectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(portLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ipLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(bsServerIPLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(connectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ipTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(portTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(connectionPanelLayout.createSequentialGroup()
                                .addComponent(unregBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                .addGap(29, 29, 29)
                                .addComponent(regtBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                            .addComponent(bsServerIPTextField, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        connectionPanelLayout.setVerticalGroup(
            connectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, connectionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(connectScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(connectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bsServerIPLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bsServerIPTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(connectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ipLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ipTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(connectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(portLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(portTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(connectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regtBtn)
                    .addComponent(unregBtn))
                .addGap(17, 17, 17))
        );

        homeTab.addTab("Connect", connectionPanel);

        details_contentTextPane.setEditable(false);
        detailsScrollPane.setViewportView(details_contentTextPane);

        details_nodeDetailsLbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        details_nodeDetailsLbl.setText("Node Details");

        details_nodeConentLbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        details_nodeConentLbl.setText("Content");

        details_idLbl.setText("ID");

        details_idDisplayLbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        details_ipDisplayLbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        details_ipLbl.setText("IP Address");

        details_portLbl.setText("Port");

        details_portDisplayLbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        details_successorLbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        details_successorLbl.setText("Successor");

        details_succidDisplayLbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        details_succidLbl.setText("ID");

        details_succipLbl.setText("IP Address");

        details_succipDisplayLbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        details_succportDisplayLbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        details_succportLbl.setText("Port");

        details_successorLbl1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        details_successorLbl1.setText("Predessor");

        details_succidLbl1.setText("ID");

        details_preidDisplayLbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        details_preipLbl.setText("IP Address");

        details_preipDisplayLbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        details_preportLbl.setText("Port");

        details_preportDisplayLbl.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        javax.swing.GroupLayout detailsPanelLayout = new javax.swing.GroupLayout(detailsPanel);
        detailsPanel.setLayout(detailsPanelLayout);
        detailsPanelLayout.setHorizontalGroup(
            detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(details_nodeDetailsLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                        .addGroup(detailsPanelLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(details_idLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(details_ipLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(details_portLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(details_ipDisplayLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(details_idDisplayLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(details_portDisplayLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(details_successorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(details_successorLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(detailsPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(detailsPanelLayout.createSequentialGroup()
                                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(details_succidLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(details_succipLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(details_succportLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(14, 14, 14)
                                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(details_succportDisplayLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(details_succipDisplayLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                        .addComponent(details_succidDisplayLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(detailsPanelLayout.createSequentialGroup()
                                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(details_succidLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(details_preipLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(details_preportLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(14, 14, 14)
                                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(details_preportDisplayLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(details_preipDisplayLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                        .addComponent(details_preidDisplayLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addGap(18, 18, 18)
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(details_nodeConentLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(detailsScrollPane))
                .addContainerGap())
        );
        detailsPanelLayout.setVerticalGroup(
            detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(details_nodeDetailsLbl)
                    .addComponent(details_nodeConentLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailsPanelLayout.createSequentialGroup()
                        .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(details_idLbl)
                            .addComponent(details_idDisplayLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(details_ipDisplayLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(details_ipLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(details_portDisplayLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(details_portLbl))
                        .addGap(30, 30, 30)
                        .addComponent(details_successorLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(details_succidLbl)
                            .addComponent(details_succidDisplayLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(details_succipDisplayLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(details_succipLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(details_succportDisplayLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(details_succportLbl))
                        .addGap(18, 18, 18)
                        .addComponent(details_successorLbl1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(details_succidLbl1)
                            .addComponent(details_preidDisplayLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(details_preipDisplayLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(details_preipLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(details_preportDisplayLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(details_preportLbl))
                        .addGap(0, 29, Short.MAX_VALUE))
                    .addComponent(detailsScrollPane))
                .addContainerGap())
        );

        homeTab.addTab("Details", detailsPanel);

        routingTextPane.setEditable(false);
        routingScrollPane.setViewportView(routingTextPane);

        javax.swing.GroupLayout routingTablePanelLayout = new javax.swing.GroupLayout(routingTablePanel);
        routingTablePanel.setLayout(routingTablePanelLayout);
        routingTablePanelLayout.setHorizontalGroup(
            routingTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(routingTablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(routingScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                .addContainerGap())
        );
        routingTablePanelLayout.setVerticalGroup(
            routingTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, routingTablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(routingScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addContainerGap())
        );

        homeTab.addTab("Routing Table", routingTablePanel);

        MainTab.addTab("Home", homeTab);

        fileIndexTextPane.setEditable(false);
        fileIndexScrollPane.setViewportView(fileIndexTextPane);

        indexTab.addTab("File ", fileIndexScrollPane);

        wordIndexTextPane.setEditable(false);
        wordIndexScrollPane.setViewportView(wordIndexTextPane);

        indexTab.addTab("Word ", wordIndexScrollPane);

        MainTab.addTab("Index", indexTab);

        downloadBtn.setText("DOWNLOAD");

        searchTextPane.setEditable(false);
        searchScrollPane.setViewportView(searchTextPane);

        searchBtn.setText("SEARCH");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(downloadBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(searchScrollPane)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addComponent(fileNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fileNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(downloadBtn)
                .addContainerGap())
        );

        MainTab.addTab("Search", searchPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainTab)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainTab)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regtBtnActionPerformed
        String bsipAddress = bsServerIPTextField.getText();
        String ipAddress = ipTextField.getText();
        String port = portTextField.getText();
        
        if(!bsipAddress.equals("") && !ipAddress.equals("") && !port.equals("")){
            bsConnector = new BSConnector(bsipAddress.trim(), ipAddress.trim(),Integer.parseInt(port.trim()));
            bsConnector.register();
            unregBtn.setEnabled(true);
        }
        else{
            JOptionPane.showMessageDialog(this,"Incomplete information"); 
        }
    }//GEN-LAST:event_regtBtnActionPerformed

    private void unregBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unregBtnActionPerformed
        bsConnector.unregister();
    }//GEN-LAST:event_unregBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        //Reset previous search results
        searchTextPane.setText("Node ID\tNode IP Adress\tUDP Port\tTCP Port\n\n");
        String fileName = fileNameTextField.getText();
        if(!fileName.equals("")){
            SearchInitializer.getInstance().localSearch(fileName);
        }
        else{
            JOptionPane.showMessageDialog(this,"Incomplete information");
        }
    }//GEN-LAST:event_searchBtnActionPerformed
    
    private void setDefaultText(){
        details_contentTextPane.setText("File ID\tFile Name\n\n");
        routingTextPane.setText("Index\tRange\tNode ID\tIP Address\tPort\n\n");
        searchTextPane.setText("Node ID\tNode IP Adress\tUDP Port\tTCP Port\n\n");
        fileIndexTextPane.setText("File ID\t\t\tNode\n\t\tIP Address\t\tPort\n\n");
        wordIndexTextPane.setText("Word ID\tFile IDs\n\n");
    }
    
    public void updateConnctionResponce(String responce){
        connectTextPane.setText(responce);
    }
    
    public void displayError(String errMsg){
        JOptionPane.showMessageDialog(this, errMsg, "Failure", JOptionPane.ERROR_MESSAGE);
    }
    
    public void updateNodeDetails(Node node){
        details_idDisplayLbl.setText(node.getId());
        details_ipDisplayLbl.setText(node.getIpAdress());
        details_portDisplayLbl.setText(String.valueOf(node.getPort()));
    }
    
    public void updateSuccessorDetails(Node successor){
        if(successor != null){
            details_succidDisplayLbl.setText(successor.getId());
            details_succipDisplayLbl.setText(successor.getIpAdress());
            details_succportDisplayLbl.setText(String.valueOf(successor.getPort()));
        }
        else{
            details_succidDisplayLbl.setText("");
            details_succipDisplayLbl.setText("");
            details_succportDisplayLbl.setText("");
        }
    }
    
    public void updatePredecessorDetails(Node predecessor){
        if(predecessor != null){
            details_preidDisplayLbl.setText(predecessor.getId());
            details_preipDisplayLbl.setText(predecessor.getIpAdress());
            details_preportDisplayLbl.setText(String.valueOf(predecessor.getPort()));
        }
        else{
            details_preidDisplayLbl.setText("");
            details_preipDisplayLbl.setText("");
            details_preportDisplayLbl.setText("");
        }
    }
    
    public void updateRoutingTable(String data){
        routingTextPane.setText(data);
    }
    
    public void updateFileIndex(String data){
        fileIndexTextPane.setText(data);
    }
    
    public void updateWordIndex(String data){
        wordIndexTextPane.setText(data);
    }
    
    public void updateContent(String content){
        details_contentTextPane.setText(content);
    }
    
    public void updateSearchResponse(String data){
        searchTextPane.setText(data);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane MainTab;
    private javax.swing.JLabel bsServerIPLbl;
    private javax.swing.JTextField bsServerIPTextField;
    private javax.swing.JScrollPane connectScrollPane;
    private javax.swing.JTextPane connectTextPane;
    private javax.swing.JPanel connectionPanel;
    private javax.swing.JPanel detailsPanel;
    private javax.swing.JScrollPane detailsScrollPane;
    private javax.swing.JTextPane details_contentTextPane;
    private javax.swing.JLabel details_idDisplayLbl;
    private javax.swing.JLabel details_idLbl;
    private javax.swing.JLabel details_ipDisplayLbl;
    private javax.swing.JLabel details_ipLbl;
    private javax.swing.JLabel details_nodeConentLbl;
    private javax.swing.JLabel details_nodeDetailsLbl;
    private javax.swing.JLabel details_portDisplayLbl;
    private javax.swing.JLabel details_portLbl;
    private javax.swing.JLabel details_preidDisplayLbl;
    private javax.swing.JLabel details_preipDisplayLbl;
    private javax.swing.JLabel details_preipLbl;
    private javax.swing.JLabel details_preportDisplayLbl;
    private javax.swing.JLabel details_preportLbl;
    private javax.swing.JLabel details_successorLbl;
    private javax.swing.JLabel details_successorLbl1;
    private javax.swing.JLabel details_succidDisplayLbl;
    private javax.swing.JLabel details_succidLbl;
    private javax.swing.JLabel details_succidLbl1;
    private javax.swing.JLabel details_succipDisplayLbl;
    private javax.swing.JLabel details_succipLbl;
    private javax.swing.JLabel details_succportDisplayLbl;
    private javax.swing.JLabel details_succportLbl;
    private javax.swing.JButton downloadBtn;
    private javax.swing.JScrollPane fileIndexScrollPane;
    private javax.swing.JTextPane fileIndexTextPane;
    private javax.swing.JTextField fileNameTextField;
    private javax.swing.JTabbedPane homeTab;
    private javax.swing.JTabbedPane indexTab;
    private javax.swing.JLabel ipLbl;
    private javax.swing.JTextField ipTextField;
    private javax.swing.JLabel portLabel;
    private javax.swing.JTextField portTextField;
    private javax.swing.JButton regtBtn;
    private javax.swing.JScrollPane routingScrollPane;
    private javax.swing.JPanel routingTablePanel;
    private javax.swing.JTextPane routingTextPane;
    private javax.swing.JButton searchBtn;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JScrollPane searchScrollPane;
    private javax.swing.JTextPane searchTextPane;
    private javax.swing.JButton unregBtn;
    private javax.swing.JScrollPane wordIndexScrollPane;
    private javax.swing.JTextPane wordIndexTextPane;
    // End of variables declaration//GEN-END:variables
}
